---
services:
  traefik:
    image: traefik:v3.6.7
    container_name: traefik-HA
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - "80:80"
      - '443:443'
      - "8080:8080" # dashboard
    enviroment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /var/traefik/certs/:./certs/:rw

networks:
  frontend:
    external: "true"