---
services:
  traefik:
    image: traefik:v3.6.7
    container_name: traefik-HA
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - '443:443'
    enviroment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/:/etc/traefik/conf/:ro
      - /var/traefik/certs/:./certs/:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-ha-https.rule=Host('traefik.ha.vdbhome.ovh')
      - traefik.http.routers.traefik-ha-https.entrypoints=websecure
      - traefik.http.routers.traefik-ha-https.tls=true

      - traefik.http.routers.traefik-ha-https.middlewares=authentik@file
      # Put the api service behind the middleware
      - traefik.http.routers.traefik-ha-https.service=api@internal

networks:
  frontend:
    external: true
  backend:
    external: true