---
services:
  transfersh:
    image: dutchcoders/transfer.sh:latest
    container_name: transfersh
    volumes:
      - ./data:/data
    environment:
      - TTL_DAYS=30
      - MAX_SIZE=10GB      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transfersh-https.rule=Host(`transfer.public.vdbhome.ovh`)"
      - "traefik.http.routers.transfersh-https.entrypoints=websecure"
      - "traefik.http.routers.transfersh-https.tls=true"
      - "traefik.http.routers.transfersh-https.tls.certresolver=cloudflare"
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true