---
services:
  transfersh:
    image: dutchcoders/transfer.sh:latest
    container_name: transfersh
    volumes:
      - ./data:/data
    environment:
      - PROVIDER=local
      - LOCAL_PATH=/data
      - TTL_DAYS=30
      - MAX_SIZE=10GB      
    labels:
      - traefik.enable=true
      - traefik.http.routers.transfersh.rule=Host(`transfer.vdbhome.ovh`)
      - traefik.http.routers.transfersh.entrypoints=web
      - traefik.http.services.transfersh.loadbalancer.server.port=8080
    restart: unless-stopped
    networks:
      - frontend

networks:
  frontend:
    external: true