---
services:
  gotify:
    image: gotify/server:2.8.0
    container_name: gotify
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      frontend:
    environment:
      - TZ=Europe/Brussels
    labels:
      - traefik.enable=true
      - traefik.http.routers.gotify-https.tls=true
      - traefik.http.routers.gotify-https.tls.certresolver=cloudflare
      - traefik.http.routers.gotify-https.rule=Host("gotify.ha.vdbhome.ovh")
      - traefik.http.routers.gotify-https.entrypoints=websecure

networks:
  frontend:
    external: true