services:
  immich-server:
    security_opt:
      - apparmor:unconfirmed
      
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.5.0
    restart: unless-stopped

    devices:
      - /dev/dri:/dev/dri

    volumes:
      - ${NFS_UPLOAD_MOUNT}:/data
      - ./cache:/cache
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - .env

    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
      - IMMICH_PUBLIC_URL=https://immich.prod.vdbhome.ovh


    labels:
      - traefik.enable=true
      - traefik.http.routers.immich-https.tls=true
      - traefik.http.routers.immich-https.tls.certresolver=cloudflare
      - traefik.http.routers.immich-https.rule=Host("immich.prod.vdbhome.ovh")
      - traefik.http.routers.immich-https.entrypoints=websecure
      - traefik.docker.network=frontend # This makes sure traefik uses the right docker network
      - traefik.http.routers.immich-https.service=immich-https-svc
      - traefik.http.services.immich-https-svc.loadbalancer.server.port=2283 # even if the port is 80

    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2283/api/server/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - backend
      - frontend

  immich-machine-learning:
    security_opt:
      - apparmor:unconfirmed
      
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.0
    restart: unless-stopped

    volumes:
      - ./cache:/cache
      - /etc/localtime:/etc/localtime:ro

    environment:
      - MACHINE_LEARNING_WORKERS=2

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

    networks:
      - backend

  redis:
    security_opt:
      - apparmor:unconfirmed
      
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

volumes:
  model-cache:

networks:
  backend:
    internal: true
  frontend:
    external: true
