---
services:
  vaultwarden:
    image: vaultwarden/server:1.35.2-alpine
    container_name: vaultwarden
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DOMAIN=https://vault.ha.vdbhome.ovh
      - SIGNUPS_ALLOWED=true 
      - DATABASE_URL=postgresql://${VAULTWARDEN_USER}:${VAULTWARDEN_PASSWORD}@postgres:5432/${VAULTWARDEN_DB}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - DISABLE_ADMIN_TOKEN=false
    volumes:
      - ./data:/data
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      # Main ui
      - traefik.http.routers.vaultwarden-https.tls=true
      - traefik.http.routers.vaultwarden-https.tls.certresolver=cloudflare
      - traefik.http.routers.vaultwarden-https.rule=Host("vault.ha.vdbhome.ovh")
      - traefik.http.routers.vaultwarden-https.entrypoints=websecure
      # Websockets
      - traefik.http.routers.vaultwarden-ws.tls=true
      - traefik.http.routers.vaultwarden-ws.tls.certresolver=cloudflare
      - traefik.http.routers.vaultwarden-ws.rule=Host("vault.ha.vdbhome.ovh") && PathPrefix("/notifications/hub")
      - traefik.http.routers.vaultwarden-ws.entrypoints=websecure
      - traefik.http.services.vaultwarden-ws.loadbalancer.server.port=3012

networks:
  frontend:
    external: true
  backend:
    external: true